"""user_uid book make non nullable

Revision ID: 090dff4a91ca
Revises: 891c77de3d1a
Create Date: 2026-04-12 02:27:19.412437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '090dff4a91ca'
down_revision: Union[str, Sequence[str], None] = '891c77de3d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'user_uid',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'user_uid',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
