"""add book tags table

Revision ID: 2635a32536f4
Revises: 879a6ac67d28
Create Date: 2026-04-13 19:27:00.331378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2635a32536f4'
down_revision: Union[str, Sequence[str], None] = '879a6ac67d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uid', name=op.f('tags_pkey'))
    )
    op.create_table('book_tags',
    sa.Column('book_uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_uid'], ['books.uid'], name=op.f('book_tags_book_uid_fkey')),
    sa.ForeignKeyConstraint(['tag_uid'], ['tags.uid'], name=op.f('book_tags_tag_uid_fkey')),
    sa.PrimaryKeyConstraint('book_uid', 'tag_uid', name=op.f('book_tags_pkey'))
    )
    # ### end Alembic commands ###
