"""fix review foreignkey

Revision ID: 9b4123bf53c5
Revises: bf3480e419c1
Create Date: 2026-04-12 19:44:26.684166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4123bf53c5'
down_revision: Union[str, Sequence[str], None] = 'bf3480e419c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reviews_book_uid_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_user_uid_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'books', ['book_uid'], ['uid'])
    op.create_foreign_key(None, 'reviews', 'users', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_user_uid_fkey'), 'reviews', 'books', ['user_uid'], ['uid'])
    op.create_foreign_key(op.f('reviews_book_uid_fkey'), 'reviews', 'users', ['book_uid'], ['uid'])
    # ### end Alembic commands ###
